virtualenvs/test19/ProyectosDjango/refugio/apps/adopcion/urls.py
from django.conf.urls import url
from apps.adopcion.views import index_adopcion,SolicitudList,SolicitudCreate

urlpatterns = [
    url(r'^index$', index_adopcion),
    url(r'^solicitud/listar$', SolicitudList.as_view(), name='solicitud_listar'),
    url(r'^solicitud/nuevo$', SolicitudCreate.as_view(), name='solicitud_crear'),


]

virtualenvs/test19/ProyectosDjango/refugio/apps/mascota/urls.py
from django.conf.urls import url
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit,mascota_delete,MascotaList,MascotaCreate,MascotaUpdate,MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo', MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^listar', MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name='mascota_editar'),    
    url(r'^eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eliminar'),    

]

virtualenvs/test19/ProyectosDjango/refugio/refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.mascota.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include ('apps.adopcion.urls', namespace="adopcion")),

]

virtualenvs/test19/ProyectosDjango/refugio/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block extrahead %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %} Document {% endblock %}</title>
</head>
<body>
<div class="container">
    {% block navbar %}
         <div class="bs-docs-section clearfix">
             <div class="row">
                <div class="col-lg-12">
                    <div class="bs-component">
                        <div class="navbar navbar-default">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                                </div>
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li class="dropdown">
                                            <a href="{% url 'mascota:mascota_listar' %}" class="dropdown-toggle" data-toggle="dropdown"
                                            role="button" aria-expanded="false">Mascotas
                                            <span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
                                                <li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="{% url 'adopcion:solicitud_listar' %}" class="dropdown-toggle" data-toggle="dropdown"
                                            role="button" aria-expanded="false">Adopcion
                                            <span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="#">Solicitar</a></li>
                                                <li><a href="#">Listar Solicitud</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="dropdown"><a href="http://www.google.com"
                                        onclick="pageTracker._link(this.href); return false;">Google</a>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="
                                            dropdown" role="button" aria-expanded="false">Opciones</a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="#">Salir</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
             </div>
         </div>
    {% endblock %}

    {% block content %}
         <h4> Bloque de Contenido </h4>
    {% endblock %}

    {% block footer %}
         
    {% endblock %}
</div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

virtualenvs/test19/ProyectosDjango/refugio/templates/base/header.html
<header>Hola</header>